# Managed by ArmFirewall Network / Routing Protocols.
router id 192.168.88.200;
hostname "meurouter";
log stderr all;

protocol device {
  scan time 10;
  interface "*";
}

protocol direct {
  interface "*";
  ipv4;
  ipv6;
}

protocol kernel {
  kernel table 254;
  learn all;
  persist;
  metric 32;
  scan time 10;
  ipv4 {
    import all;
    export all;
  };
  ipv6 {
    import all;
    export all;
  };
}

protocol rip {
  ipv4 {
    import all;
    export none;
  };
  interface "enp0s10", "enp0s8" {
    mode multicast;
    update time 30;
    timeout time 180;
    garbage time 120;
    passive no;
    authentication cryptographic;
    password "teste";
  };
}
