# Managed by ArmFirewall Network / Routing Protocols.
router id 192.168.88.200;
hostname "meurouter";
log syslog all;

protocol device {
  scan time 10;
  interface "enp0s10";
  ipv4;
  ipv6;
}

protocol direct {
  interface "enp0s8";
  ipv4;
  ipv6;
}

protocol kernel {
  kernel table 254;
  learn all;
  persist;
  metric 32;
  scan time 10;
  ipv4 {
    table main;
    import all;
    export none;
  };
}
