"""Global constants shared across ArmFirewall modules."""

from __future__ import annotations

from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]



DB_DIR = ROOT_DIR / "db"
CONF_DIR = ROOT_DIR / "conf"
OCI_CONF_DIR = CONF_DIR / "oci"
OCI_PRIVATE_KEY_PATH = OCI_CONF_DIR / "oci_privatekey.pem"
OCI_CONFIG_PATH = OCI_CONF_DIR / "oci.config"
LOG_DIR = ROOT_DIR / "logs"
SUPERVISOR_CONF = CONF_DIR / "supervisord.conf"
IFACE_DB_PATH = DB_DIR / "iface.db"
LOG_DB_PATH = DB_DIR / "logs.db"
USERS_DB_PATH = DB_DIR / "users.db"
WORK_REQUEST_DB_PATH = DB_DIR / "work-requests.db"
SERVICES_DB_PATH = DB_DIR / "services.db"
DNSMASQ_DB_PATH = DB_DIR / "dnsmasq.db"
LATENCY_DB_PATH = DB_DIR / "latency.db"
LINKFAILOVER_DB_PATH = DB_DIR / "linkfailover.db"
POLICY_ROUTING_DB_PATH = DB_DIR / "policy-routing.db"
LIBRESWAN_DB_PATH = DB_DIR / "libreswan.db"
RUNTIME_SETTINGS_DB_PATH = DB_DIR / "runtime_settings.db"

BIRD_DB_PATH = DB_DIR / "bird.db"
BIRD_DDL_PATH = DB_DIR / "ddl" / "bird.ddl"
BIRD_CONFIG_PATH = CONF_DIR / "bird.conf"
BIRD_LOG_PATH = LOG_DIR / "bird.out.log"
BIRD_ERR_LOG_PATH = LOG_DIR / "bird.err.log"
BIRD_ANY_INTERFACE = "*"
BIRD_DEFAULT_CHANNEL_TABLE_NAME = "main"
BIRD_DEFAULT_ROUTER_ID = "192.0.2.1"
BIRD_DEFAULT_HOSTNAME = "armfirewall"
BIRD_IMPORT_EXPORT_VALUES = {"all", "none"}
BIRD_CHANNEL_FAMILIES = {"ipv4", "ipv6", "ipv4/ipv6"}
BIRD_RIP_VERSIONS = {"1", "2", "ng"}
BIRD_RIP_MODES = {"multicast", "broadcast"}
BIRD_RIP_AUTHENTICATIONS = {"none", "plaintext", "cryptographic"}
BIRD_BGP_SESSION_TYPES = {"auto", "ibgp", "ebgp"}

ADAM_DATASET_DIR = ROOT_DIR / "daemons" / "adamd" / "datasets"
ADAM_DATASET_MAX_BYTES = 5 * 1024 * 1024
ADAM_DATASET_MAX_ROWS = 100_000
ADAM_DATASET_REQUIRED_COLUMNS = ("text", "label")
ADAM_DATASET_TYPES = {"training", "testing"}
ADAM_DATASET_CATEGORIES = {
    "adam_misc": "Adam Misc",
    "firewall": "Firewall",
    "greetings": "Greetings",
    "ner": "NER",
}
ADAM_TEXT_CLASSIFIER_DATASET_CATEGORIES = {"adam_misc", "firewall", "greetings"}
ADAM_MODELS_DIR = ROOT_DIR / "daemons" / "adamd" / "models"
ADAM_CHARTS_DIR = ROOT_DIR / "daemons" / "adamd" / "charts"
ADAM_DELETE_STAGING_DIR = ROOT_DIR / "daemons" / "adamd" / ".delete-staging"
ADAM_TEXT_CLASSIFIER_MODEL_FILENAME = "text_classifier.joblib"
ADAM_TEXT_CLASSIFIER_MODEL_PATH = (
    ADAM_MODELS_DIR / ADAM_TEXT_CLASSIFIER_MODEL_FILENAME
)
ADAM_TEXT_CLASSIFIER_MAX_ITERATIONS = 1_000
ADAM_TEXT_CLASSIFIER_RANDOM_STATE = 42
ADAM_TEXT_CLASSIFIER_CHART_DPI = 120
ADAM_TEXT_CLASSIFIER_CHART_FILENAME_PREFIX = "text_classifier"
ADAM_SPEECH_LANGUAGE_PT_BR = "pt-BR"
ADAM_SPEECH_LANGUAGE_EN_US = "en-US"
ADAM_SPEECH_MODEL_PT_BR_URL = "/static/models/vosk-model-small-pt-0.3.tar.gz"
ADAM_SPEECH_MODEL_EN_US_URL = "/static/models/vosk-model-small-en-us-0.15.tar.gz"
ADAM_WAKE_WORD_PT_BR = "Adão"
ADAM_WAKE_WORD_EN_US = "Adam"
ADAM_WAKE_WORD_ALIASES_PT_BR = ("Adão", "Adan")
ADAM_WAKE_WORD_ALIASES_EN_US: tuple[str, ...] = ()
ADAM_WAKE_TRANSCRIPTION_ALIASES_PT_BR = ("Adão", "Adan", "a dão")
ADAM_WAKE_TRANSCRIPTION_ALIASES_EN_US = ("either", "add them", "at them", "madam")
ADAM_WAKE_PROFILE_KEY_PT_BR = "default"
ADAM_WAKE_PROFILE_KEY_EN_US = "en-US:adam"
ADAM_SPEECH_LANGUAGE = ADAM_SPEECH_LANGUAGE_EN_US
ADAM_SPEECH_MODEL_URL = ADAM_SPEECH_MODEL_EN_US_URL
ADAM_WAKE_WORD = ADAM_WAKE_WORD_EN_US
ADAM_WAKE_WORD_ALIASES = ADAM_WAKE_WORD_ALIASES_EN_US
ADAM_WAKE_TRANSCRIPTION_ALIASES = ADAM_WAKE_TRANSCRIPTION_ALIASES_EN_US
ADAM_WAKE_PROFILE_KEY = ADAM_WAKE_PROFILE_KEY_EN_US
ADAM_WAKE_WORD_MIN_CONFIDENCE = 0.55
ADAM_WAKE_WORD_ENGINE_URL = "/static/vendor/vosk-browser/vosk.js"
ADAM_WAKE_WORD_MODEL_URL = ADAM_SPEECH_MODEL_URL
ADAM_WAKE_WORD_WORKLET_URL = "/static/js/adam_wake_word_processor.js?v=20260722-fixed-16khz-resampling"
ADAM_WAKE_DETECTOR_WORKER_URL = "/static/js/adam_wake_detector_worker.js?v=20260722-sliding-window-preroll"
ADAM_WAKE_ENROLLMENT_SAMPLES = 5
ADAM_WAKE_ENROLLMENT_DURATION_MS = 1_200
ADAM_WAKE_DETECTION_INTERVAL_MS = 250
ADAM_WAKE_DETECTION_STREAK = 2
ADAM_WAKE_DETECTION_THRESHOLD_MULTIPLIER = 1.6
ADAM_WAKE_PRE_ROLL_MS = 5_000
ADAM_COMMAND_MIN_CAPTURE_MS = 1_500
ADAM_COMMAND_SAMPLE_RATE = 16_000
ADAM_COMMAND_TRAILING_SILENCE_MS = 1_200
ADAM_COMMAND_SILENCE_THRESHOLD = 0.004
ADAM_COMMAND_TIMEOUT_MS = 12_000
ADAM_TRANSCRIPTION_MAX_CHARS = 2_000
ADAM_LISTENING_STORAGE_KEY = "armfirewall.adam.listening-enabled"
ADAM_DB_PATH = DB_DIR / "adam.db"
ADAM_DDL_PATH = DB_DIR / "ddl" / "adam.ddl"
ADAM_WORK_REQUEST_CATEGORY = "ADAM.MODEL_TRAINING"
ADAM_WORK_REQUEST_ACTION = "train"
ADAM_WORK_REQUEST_DELETE_ACTION = "delete"
ADAM_WORK_REQUEST_TARGET = "model_training"
ADAM_LOG_SOURCE = "adamd/adamd.py"
ADAM_SYSTEMD_RUN_PATH = Path("/usr/bin/systemd-run")
ADAM_TRAINING_CPU_QUOTA_PERCENT = 25
ADAM_TRAINING_MEMORY_HIGH_BYTES = 384 * 1024 * 1024
ADAM_TRAINING_MEMORY_MAX_BYTES = 512 * 1024 * 1024
ADAM_TRAINING_TASKS_MAX = 32
ADAM_TRAINING_NICE = 10
ADAM_TRAINING_MAX_THREADS = 1
ADAM_TRAINING_RUNTIME_MAX_SECONDS = 240
ADAM_TRAINING_OOM_POLICY = "stop"

RRD_DIR = ROOT_DIR / "rrd"
RRD_IMG_DIR = RRD_DIR / "img"
